Repository 2024-WinterBootcamp-Team-E/backend, pull requests merged in 2025-01, with the labels that each got.

#7 [set/#1] mysql환경세팅과 파일구조 수정
  app/database/session.py
  app/main.py
  app/routers/api.py
  app/routers/users.py
  app/schemas/user.py
  app/services/user.py
Labels: ⚙ Setting

#10 [feat]사용자 hard, soft delete 구현완료
  app/models/user.py
  app/routers/users.py
  app/schemas/ResultResponseModel.py
  app/schemas/user.py
  app/services/user.py
  app/services/user_service.py
Labels: ✨ Feature

#12 [feat] 사용자 정보 수정 기능
  app/models/user.py
  app/routers/users.py
  app/schemas/user.py
  app/services/user_service.py
  default.db
Labels: ✨ Feature

#21 [feat/#5] 채팅방 삭제 조회 기능 추가
  app/main.py
  app/models/__init__.py
  app/models/character.py
  app/models/chat.py
  app/models/feedback.py
  app/models/sentence.py
  app/models/user.py
  app/routers/api.py
  app/routers/chat.py
  app/schemas/character.py
  app/schemas/chat.py
  app/schemas/feedback.py
  app/schemas/sentence.py
  app/services/chat_service.py
Labels: ✨ Feature

#24 [feat/#7] 특정 사용자 조회 기능 추가
  Dockerfile
  app/main.py
  app/models/__init__.py
  app/models/chat.py
  app/models/feedback.py
  app/models/sentence.py
  app/models/user.py
  app/routers/chat.py
  app/routers/users.py
  app/schemas/chat.py
  app/schemas/feedback.py
  app/schemas/sentence.py
  app/schemas/user.py
  app/services/chat_service.py
  app/services/feedback_service.py
  app/services/user_service.py
  docker-compose.yml
Labels: ✨ Feature

#23 [feat/#8] 모든 채팅방 조회 기능 추가
  app/routers/chat.py
  app/schemas/character.py
  app/schemas/feedback.py
  app/services/chat_service.py
  default.db
Labels: ✨ Feature

#25 [bug/#9] 회원가입 기능 추가
  app/routers/users.py
  app/schemas/user.py
  app/services/user_service.py
Labels: 🐞 BugFix

#28 [feat/#6] 상황별 모든 문장 조회기능 추가
  app/models/sentence.py
  app/routers/api.py
  app/routers/sentence.py
  app/schemas/sentence.py
  app/services/speech_service.py
Labels: ✨ Feature

#30 [feat/#10] 로그인 기능 구현
  app/routers/users.py
  app/schemas/user.py
  app/services/user_service.py
Labels: ✨ Feature

#31 [feat/#11] 캐릭터 목록 조회
  app/routers/api.py
  app/routers/character.py
  app/routers/chat.py
  app/routers/users.py
  app/services/character_service.py
  default.db
Labels: ✨ Feature

#32 [refactor/#12] 모델 수정
  app/database/session.py
  app/models/character.py
  app/models/chat.py
  app/models/feedback.py
  app/models/sentence.py
  app/models/user.py
  app/routers/api.py
  app/routers/chat.py
  app/routers/sentence.py
  app/routers/users.py
  app/schemas/ResultResponseModel.py
  app/schemas/character.py
  app/schemas/chat.py
  app/schemas/feedback.py
  app/schemas/sentence.py
  app/schemas/user.py
  app/services/chat_service.py
  app/services/feedback_service.py
  app/services/speech_service.py
Labels: 🔨 Refactor

#33 [feat#13] s3버킷 업로드API 기능 수정
  app/__init__.py
  app/config/aws/__init__.py
  app/config/aws/s3Clent.py
  app/config/elevenlabs/__init__.py
  app/config/elevenlabs/text_to_speech_stream.py
  app/config/openAI/__init__.py
  app/config/openAI/chatgpt.py
  app/config/openAI/whisper.py
  app/models/sentence.py
  app/routers/users.py
  requirements.txt
Labels: ✨ Feature

#35 [feat/#14] 스피치 문장 조회 기능 추가
  app/routers/sentence.py
Labels: ✨ Feature

#39 [refactor/#15] 회원가입 및 로그인 기능 리팩토링
  app/routers/users.py
  app/services/user_service.py
Labels: 🔨 Refactor

#40 [refactor/#16] 테이블 delete cascade 추가 및 스키마 수정
  app/main.py
  app/models/character.py
  app/models/chat.py
  app/models/feedback.py
  app/models/sentence.py
  app/routers/character.py
  app/routers/chat.py
  app/routers/users.py
  app/schemas/character.py
  app/schemas/chat.py
  app/schemas/feedback.py
  app/schemas/sentence.py
  app/schemas/user.py
  app/services/character_service.py
  app/services/feedback_service.py
Labels: 🔨 Refactor

#44 [refactor/#18] : 캐릭터 모델에 이미지 url 필드 추가및 캐릭터 목록 조회 api 수정
  app/models/character.py
  app/routers/character.py
  app/schemas/character.py
Labels: 🔨 Refactor

#52 [feat/#21] : 유저 이미지 파일 업로드 및 URL 반환 기능 추가
  app/models/character.py
  app/models/user.py
  app/routers/users.py
  app/schemas/user.py
Labels: ✨ Feature

#55 [feat/#22] : openai 프롬프트 추가 및 response와 문법 결과 변환 완료
  app/config/elevenlabs/text_to_speech_stream.py
  app/config/openAI/openai_service.py
  app/models/character.py
  app/routers/chat.py
  app/services/chat_service.py
Labels: 🐞 BugFix, ✨ Feature

#56 [refactor/#23]:비즈니스 로직을 트랜잭션으로 수정 및 코드 스타일 통일
  app/config/aws/s3Clent.py
  app/routers/sentence.py
  app/routers/users.py
  app/services/speech_service.py
Labels: 🔨 Refactor

#58 [feat/#24] : MongoDB 추가
  app/config/openAI/openai_service.py
  app/database/session.py
  app/main.py
  app/routers/chat.py
  app/services/chat_service.py
  docker-compose.yml
  requirements.txt
Labels: ✨ Feature

#65 [feat/#26] 오픈ai azure 추가
  app/config/azure/__init__.py
  app/config/azure/pronunciation_feedback.py
  app/config/openAI/openai_service.py
  app/models/bubble.py
  app/models/character.py
  app/models/feedback.py
  app/routers/api.py
  app/routers/feedback.py
  app/routers/sentence.py
  app/services/feedback_service.py
  requirements.txt
Labels: ✨ Feature

#64 [feat/#27]캐릭터 테이블 버블 테이블 삭제 및 반환 변경
  app/config/constants.py
  app/config/elevenlabs/text_to_speech_stream.py
  app/config/openAI/openai_service.py
  app/database/session.py
  app/models/__init__.py
  app/models/character.py
  app/models/chat.py
  app/models/feedback.py
  app/models/sentence.py
  app/models/user.py
  app/routers/api.py
  app/routers/character.py
  app/routers/chat.py
  app/routers/sentence.py
  app/routers/test.py
  app/routers/users.py
  app/schemas/character.py
  app/schemas/chat.py
  app/schemas/feedback.py
  app/schemas/user.py
  app/services/character_service.py
  app/services/chat_service.py
  app/services/user_service.py
  your_script_name.py
Labels: 🔨 Refactor

#68 [feat/#28]: 대화 흐름에 기반한 프롬프트 생성 코드 작성 기능
  app/config/openAI/openai_service.py
  app/routers/users.py
  app/services/chat_service.py
Labels: ✨ Feature

#70 [feat/#29]: 피드백 테이블에 정확성, 유창성, 완전성, 발음 점수 추가
  app/config/azure/pronunciation_feedback.py
  app/models/feedback.py
  app/routers/feedback.py
  app/services/feedback_service.py
  app/services/user_service.py
Labels: ✨ Feature

#72 [feat/#30]: 평가점수 평균조회 API 구현
  app/routers/feedback.py
  app/services/feedback_service.py
Labels: ✨ Feature

#75 [refactor/#9]: 평가점수 평균조회 API 수정
  app/routers/feedback.py
Labels: 🔨 Refactor

#76 [refactor/#32]: 모든 api 테스트 및 수정 (1)
  app/config/aws/s3Clent.py
  app/config/constants.py
  app/database/session.py
  app/models/character.py
  app/models/chat.py
  app/models/feedback.py
  app/models/sentence.py
  app/routers/chat.py
  app/routers/feedback.py
  app/routers/sentence.py
  app/routers/test.py
  app/routers/users.py
  app/schemas/character.py
  app/schemas/chat.py
  app/schemas/feedback.py
  app/schemas/user.py
  app/services/character_service.py
  app/services/chat_service.py
  app/services/feedback_service.py
  app/services/speech_service.py
  app/services/user_service.py
Labels: 🔨 Refactor

#78 [refactor/#33]: 모니터링 추가
  app/main.py
  docker-compose.yml
  prometheus.yml
  requirements.txt
Labels: ✨ Feature

#82 [feat/#35]: 출석체크 기능 구현
  app/routers/users.py
  app/services/user_service.py
Labels: ✨ Feature

#85 [set/#36]: fastapi CORS 설정 추가
  app/main.py
Labels: ⚙ Setting

#87 [refactor/#36]: 특정사용자조회 api 수정
  app/routers/users.py
  app/schemas/user.py
Labels: 🔨 Refactor

#88 [refactor/#38]: 비동기 및 채팅 대화생성 SSE 변환
  Dockerfile
  app/config/constants.py
  app/config/elevenlabs/text_to_speech_stream.py
  app/config/openAI/openai_service.py
  app/routers/chat.py
  app/services/chat_service.py
  requirements.txt
Labels: 🔨 Refactor

#90 [feat/#39] 발음분석을 SSE를 활용한 청크 단위 데이터 스트리밍 구현
  Dockerfile
  app/config/azure/pronunciation_feedback.py
  app/config/openAI/openai_service.py
  app/routers/feedback.py
Labels: ✨ Feature

#97 [refactor/#40]: api 테스트 및 수정
  app/routers/chat.py
  app/schemas/feedback.py
  app/schemas/user.py
  app/services/speech_service.py
Labels: 🔨 Refactor

#98 [feat/#41] 비동기 몽고디비 추가 및 발음분석결과 필터링 기능 추가
  app/config/azure/pronunciation_feedback.py
  app/config/openAI/openai_service.py
  app/database/session.py
  app/routers/feedback.py
  app/services/feedback_service.py
  docker-compose.yml
Labels: ✨ Feature

#119 [refactor/#44]: 코드 수정
  app/config/openAI/openai_service.py
  app/models/chat.py
  app/routers/chat.py
  app/schemas/chat.py
  app/services/chat_service.py
Labels: 🔨 Refactor

#125 [feat/#46] 사용자별 당일 학습 정보 조회 기능 구현
  app/routers/test.py
  app/schemas/test.py
  app/services/test_service.py
Labels: ✨ Feature

#130 [refactor/#47] 상황별 문장조회 api 수정
  app/routers/sentence.py
Labels: 🔨 Refactor

#133 [feat/#48]: 채팅방 생성시 채팅방 전체 목록 조회 기능
  app/routers/chat.py
Labels: ✨ Feature

#135 [refactor/#49]: 발음 분석 데이터폼 수정
  app/main.py
  app/routers/feedback.py
  app/services/feedback_service.py
  docker-compose.yml
  prometheus.yml
  requirements.txt
  test.js
Labels: 🔨 Refactor

#139 [refactor/#51]: 출석체크 응답시간 단축 및 일수 늘림
  Dockerfile
  app/models/user.py
  app/routers/users.py
  app/services/user_service.py
Labels: 🔨 Refactor

#140 [refactor/#52]: 발음약점 저장 필터링 및 발음점수 난이도 상승
  app/config/azure/pronunciation_feedback.py
  app/routers/feedback.py
  app/services/feedback_service.py
Labels: 🔨 Refactor

#150 [refactor/#53]: istudy관련 api연동 중 수정사항
  app/config/constants.py
  app/config/elevenlabs/text_to_speech_stream.py
  app/routers/chat.py
  app/schemas/chat.py
  app/services/chat_service.py
Labels: 🔨 Refactor

#156 [refactor/#54] 일레븐랩스 작동 방식 수정
  app/config/elevenlabs/text_to_speech_stream.py
  app/models/chat.py
  app/services/chat_service.py
  docker-compose.yml
Labels: 🔨 Refactor

#160 [refactor/#56] gpt 프롬프트 수정
  app/config/azure/pronunciation_feedback.py
  app/config/openAI/openai_service.py
  app/routers/chat.py
Labels: 🔨 Refactor

#163 [refactor/#57]: 코드 가독성을 높이고 불필요한 주석을 제거
  app/config/aws/s3Clent.py
  app/config/azure/pronunciation_feedback.py
  app/config/constants.py
  app/config/elevenlabs/text_to_speech_stream.py
  app/config/openAI/openai_service.py
  app/database/session.py
  app/main.py
  app/models/user.py
  app/routers/api.py
  app/routers/chat.py
  app/routers/feedback.py
  app/routers/sentence.py
  app/routers/test.py
  app/routers/users.py
  app/schemas/chat.py
  app/schemas/test.py
  app/schemas/user.py
  app/services/chat_service.py
  app/services/feedback_service.py
  app/services/speech_service.py
  app/services/test_service.py
  app/services/user_service.py
  requirements.txt
  your_script_name.py
Labels: 🔨 Refactor

#164 [refactor/#58]: istudy관련 api 수정
  app/config/openAI/openai_service.py
  app/routers/feedback.py
  app/services/chat_service.py
Labels: 🔨 Refactor

#169 [refactor/#59]: pstudy관련 api 수정
  app/config/azure/pronunciation_feedback.py
  app/config/openAI/openai_service.py
  app/routers/feedback.py
  app/services/feedback_service.py
Labels: 🔨 Refactor

#172 [refactor/#59]:프롬프트수정
  app/config/azure/pronunciation_feedback.py
  app/config/openAI/openai_service.py
  app/services/feedback_service.py
Labels: 🔨 Refactor
